plugins {
  id 'com.android.library'
}

group 'com.travelunion.flutter_zendesk_chat'
version '1.0'

android {
  namespace "com.travelunion.flutter_zendesk_chat"

  compileSdkVersion 34 // or flutter.compileSdkVersion if available in your setup

  defaultConfig {
    minSdkVersion 21 // or flutter.minSdkVersion
  }

  lint {
    disable 'InvalidPackage'
  }
}

dependencies {
  implementation "com.zendesk:chat-providers:3.6.0"
  implementation "com.google.code.gson:gson:2.10.1"
}
