plugins {
    id 'com.android.library'
}

buildscript {
  repositories {
    google()
    jcenter()
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:8.2.1'
  }
}

android {
  namespace "com.travelunion.flutter_zendesk_chat"
  compileSdkVersion 34

  defaultConfig {
    minSdkVersion 21
  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}

allprojects {
  repositories {
    google()
    mavenCentral()
    maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
  }
}

dependencies {
  implementation group: 'com.zendesk', name: 'messaging', version: '5.3.0'
  implementation group: 'com.zendesk', name: 'chat', version: '3.6.0'
}