rootProject.name = 'flutter_zendesk_chat'

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://zendesk.jfrog.io/zendesk/repo/" }
    }
}


plugins {
    // Android Gradle Plugin versions for modules in this build
    id 'com.android.library' version '7.3.0' apply false

    // Only needed if some module is an application (example app)
    id 'com.android.application' version '7.3.0' apply false
}
