enum DeliveryStatus {
  CANCELLED,
  DELIVERED,
  FAILED_FILE_SENDING_DISABLED,
  FAILED_FILE_SIZE_TOO_LARGE,
  FAILED_INTERNAL_SERVER_ERROR,
  FAILED_RESPONSE_TIMEOUT,
  FAILED_UNKNOWN_REASON,
  FAILED_UNSUPPORTED_FILE_TYPE,
  PENDING,
  UNKNOWN,
}